const MANUAL = {
  // Root screens
  ROOT: 'ROOT',
  // Other screen
  ADD_TASK_SCREEN: 'ADD_TASK_SCREEN',
  EDIT_TASK_SCREEN: 'EDIT_TASK_SCREEN',
  DELETE_TASK_SCREEN: 'DELETE_TASK_SCREEN',
  DETAIL_TASK_SCREEN: 'DETAIL_TASK_SCREEN',
} as const;

export default {MANUAL};
